version: "3.8"

services:
  mkdocs:
    build:
      context: .
    ports:
      - "3002:8000"
    volumes:
      - ./docs:/docs/docs
      - ./mkdocs.yml:/docs/mkdocs.yml
    restart: unless-stopped
